language: julia
os:
    - linux
julia:
    - nightly
    - v0.4.0-rc2
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("StochasticSearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
