language: julia
os:
    - linux
julia:
    - release
    - nightly
    - 0.4.0-rc1
    - 0.3.2
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("StochasticSearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
