language: julia
os:
    - linux
julia:
    - release
notifications:
    email: false

-script:        
    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
    - PKGADD="FactCheck"
    - julia -e 'for p in split(ENV["PKGADD"],";") Pkg.add(p) end'      
    - julia --code-coverage test/runtests.jl; fi
after_success:
    - julia -e 'cd(Pkg.dir("StochasticSearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
